### ISSUE TITLE
"후기" 카테고리 접근 안되는 버그

### ISSUE THREAD

**Issue by gusah009** [gusah009/gusah009.github.io#10]
<img width="1175" alt="image" src="https://user-images.githubusercontent.com/26597702/192924350-8374d3b2-ccae-4e74-9adf-984e34c9327d.png">

"후기" 카체고리에 접근하면 위와 같은 버그가 발생합니다. 

한글 카테고리라 그런 것 같은데, 정확한 원인은 잘 모르겠습니다.

**Comment by publdaze** [comment]
카테고리의 href에는 영어로만 구성하는 걸로 하겠습니다.
