### ISSUE TITLE
배포 시 포스팅의 상단 Title이 밑으로 내려가는 문제

### ISSUE THREAD

**Issue by gusah009** [gusah009/gusah009.github.io#15]
## 배포 환경
아래 두 이미지는 배포 환경에서의 포스팅 상태입니다.

<img width="500" alt="스크린샷 2022-10-05 오후 6 53 29" src="https://user-images.githubusercontent.com/26597702/194033674-6deec966-eb66-4184-995d-b1faba29c21c.png">
<img width="500" alt="스크린샷 2022-10-05 오후 6 53 53" src="https://user-images.githubusercontent.com/26597702/194033692-6cd76bbd-cb59-43de-be90-e2bee3633f6f.png">

`relative` 유무에 따라 글이 올라가고 내려가는 것을 확인할 수 있습니다.

## 로컬 환경

이유는 모르겠지만 로컬환경에서는 `relative`가 자동으로 꺼져있습니다.
<img width="748" alt="스크린샷 2022-10-05 오후 6 54 47" src="https://user-images.githubusercontent.com/26597702/194033693-596c1e5e-b460-42fe-81e2-afb0451f2bcc.png">

**Comment by publdaze** [comment]
해결 완 (63352228e5a5642a74f109b6434a334a71898c81)
