### ISSUE TITLE
코드 색상 변경

### ISSUE THREAD

**Issue by gusah009** [gusah009/gusah009.github.io#2]
<img width="1395" alt="스크린샷 2022-09-29 오전 10 43 22" src="https://user-images.githubusercontent.com/26597702/192919697-1e3df29c-387f-475e-8f6d-ed4be075ab79.png">

- [x] 어노테이션 색상 vscode에 맞게 변경
- [x] for, if, return 색상 vscode에 맞게 변경
- [x] 상수 색상 vscode에 맞게 변경
- [x] function 색상 vscode에 맞게 변경

**Comment by publdaze** [comment]
6bd97466bc79d6aa4e16ec4a177fbb5f56dcaa41
