### ISSUE TITLE
포스팅 폭 늘리기

### ISSUE THREAD

**Issue by gusah009** [gusah009/gusah009.github.io#24]
포스팅 폭을 조금 더 늘리는 게 좋을 것 같습니다.

16:9 비율의 사진이 너무 작게 보입니다.

**Comment by publdaze** [comment]
![image](https://user-images.githubusercontent.com/78250089/197196490-12347fd2-d7c0-42ad-87f5-e4cc860519cf.png)
![image](https://user-images.githubusercontent.com/78250089/197197207-0f996fdf-b014-4cc2-bc0e-f8f1594873bd.png)
<img width="1728" alt="image" src="https://user-images.githubusercontent.com/78250089/197197772-83bb0237-b5ad-41ef-898f-6acdc9afce11.png">

@gusah009 원래 포스팅 폭과 소개글, 포스팅 목록 폭을 동일하게 해놓았었는데 맨 아래 사진처럼 마찬가지로 늘리는 게 좋을까요?

**Comment by gusah009** [comment]
넵! 더 늘리는 게 좋을 것 같습니다.

혹시 맨 아래 사진에서 더 늘릴 순 없는 건가요?

**Comment by publdaze** [comment]
더 늘릴 수는 있는데 너무 퍼져보이지 않을까해서.. 어느정도 늘릴길 원하시나요?

**Comment by publdaze** [comment]
44ed8ed3946619c378ab6416c3932cea6a1cdd5c
