### ISSUE TITLE
포스팅 제목 overflow 처리

### ISSUE THREAD

**Issue by publdaze** [gusah009/gusah009.github.io#30]
<img width="898" alt="image" src="https://user-images.githubusercontent.com/78250089/197193995-6b09f2fa-a6dd-49cc-b400-a31ecf9e3821.png">

`키퍼 홈페이지 리뉴얼 8 - 스케줄러와 Transaction 그리고 테스트 코드에서 생긴 문제 해결하기` 라는 제목의 포스팅인데 `overflow` 됐을 때 `...` 처리되는 거 괜찮나요?

**Comment by gusah009** [comment]
다른 곳에서 제목을 볼 수 있는 곳이 있나요?

**Comment by publdaze** [comment]
<img width="1728" alt="image" src="https://user-images.githubusercontent.com/78250089/197200442-33fc4370-68fd-43bc-a477-fe7efb299d9e.png">
<img width="926" alt="image" src="https://user-images.githubusercontent.com/78250089/197200147-a8bab7f3-a769-41aa-a910-5f7cc4e67ee7.png">

창크기 조절해서 보기 혹은 url..ㅎ 말고는 제목 볼 수 없습니다..!

**Comment by gusah009** [comment]
음... 제가 그럼 포스팅 할 때 타이틀을 한번 더 언급하겠습니다!

...으로 가려도 될 것 같습니다!
