### ISSUE TITLE
numbering이 안되는 문제

### ISSUE THREAD

**Issue by gusah009** [gusah009/gusah009.github.io#35]
<img width="2558" alt="image" src="https://github.com/gusah009/gusah009.github.io/assets/26597702/2f72ae1e-7732-4509-8e38-151c9f5f1d35">

`1. 2. 3.` 으로 넘버링을 해도 블로그에선 `-`로 나옵니다 ㅠㅠ

**Comment by publdaze** [comment]
해결 완료 후 재배포 하였습니다.

이제 넘버링 정상 동작합니다!
<img width="300" alt="image" src="https://github.com/gusah009/gusah009.github.io/assets/78250089/3e1d13c3-4a8d-40a3-8479-b11e9d0af30a">
