### ISSUE TITLE
X 표시 위치 변경 요청

### ISSUE THREAD

**Issue by gusah009** [gusah009/gusah009.github.io#4]
아래와 같이 X 표시가 안보이는 문제가 있음.

<img width="250" alt="스크린샷 2022-09-29 오전 10 49 42" src="https://user-images.githubusercontent.com/26597702/192920316-df28c8b8-d63c-4e7f-bb70-c7e3818889f7.png">
<img width="250" alt="스크린샷 2022-09-29 오전 10 49 49" src="https://user-images.githubusercontent.com/26597702/192920320-d8fbe16f-0146-4fd2-987e-5fc6ab59e9e6.png">
<img width="250" alt="스크린샷 2022-09-29 오전 10 49 53" src="https://user-images.githubusercontent.com/26597702/192920323-16b7374c-6917-49c3-93d9-31ff40ed36ef.png">

아래 위치로 이동시켜 주시면 감사하겠습니다.

<img width="400" alt="스크린샷 2022-09-29 오전 10 52 21" src="https://user-images.githubusercontent.com/26597702/192920564-c4bcbc77-a6df-4c69-b55f-6015eac4564e.png">

- [x] X 표시 위치 변경 요청

**Comment by publdaze** [comment]
반응형의 경우 
<img width="400" alt="image" src="https://user-images.githubusercontent.com/78250089/192994233-a3312897-1118-4db8-81f3-44f8ce13a8b2.png">
이런식으로 X 표시해주는데
통일하는 게 좋을 것 같습니다!

제안해주신 X 위치는 저도 생각해봤으나 배치가 다른 요소들과 함께 봤을 때 조금 어색하지 않을까하는 우려가 있고,
사진과 같은 X는 웹 크기의 경우 보통 사이드바가 열려있을텐데  계속 떠있으면 거슬리지 않을까하는 우려가 있습니다.

더 선호하는 디자인 말해주시면 그렇게 수정하겠습니다!

**Comment by gusah009** [comment]
현재 블로그에 반응형 웹 뷰의 종류로 **[모바일 뷰], [웹 절반 뷰], [웹 전체화면 뷰]** 총 3가지가 있는 것 같습니다.

각각의 종류에 따라 아래와 같이 해주시면 감사하겠습니다.

**[모바일 뷰]:** X자 없이 어두워진 부분 클릭 시 사이드바 닫힘
**[웹 절반 뷰]:** X자의 위치는 상관없지만 있는듯 없는듯 했으면 좋겠습니다! 😂
**[웹 전체화면 뷰]:** **[웹 절반 뷰]:**와 동일하게 가져가면 될 것 같습니다!

**Comment by publdaze** [comment]
<img width="320" alt="image" src="https://user-images.githubusercontent.com/78250089/193301818-850ccb5d-0621-49e5-a9a4-c81a96eefbb9.png"> <img width="319" alt="image" src="https://user-images.githubusercontent.com/78250089/193303204-e0088b27-5108-4aa7-a33c-63bd6ca34602.png">

어떤 X가 좋으신가요?

**Comment by gusah009** [comment]
> ![image](https://user-images.githubusercontent.com/26597702/193392171-2d1de2b4-6104-4462-ab34-0432ef2ed75a.png)

이게 더 좋습니다!
