### ISSUE TITLE
li 표시 안되는 버그 

### ISSUE THREAD

**Issue by gusah009** [gusah009/gusah009.github.io#5]
<img width="1286" alt="image" src="https://user-images.githubusercontent.com/26597702/192920781-035c916e-c221-4e1f-9889-028cc0b3a8ea.png">

`<li>` 태그에 동그라미 표시가 안됩니다.

+ `<ul>` `top, bottom margin`이 너무 큰 것 같습니다!

**Comment by publdaze** [comment]
<img width="750" alt="image" src="https://user-images.githubusercontent.com/78250089/196223146-59ea7733-750e-4484-a96d-2032da20417b.png">

`top, bottom` 이정도 간격이면 괜찮을까요?
