### ISSUE TITLE
우측 상단 불필요한 툴팁

### ISSUE THREAD

**Issue by gusah009** [gusah009/gusah009.github.io#8]
<img width="225" alt="image" src="https://user-images.githubusercontent.com/26597702/192922012-e588fc36-609f-4493-8cb2-7d78c7c1bf34.png">

우측 상단을 누르면 세 가지 툴팁이 뜨는데, 불필요해 보입니다.

- [x] 우측 상단 툴팁 제거
- [x] `whoami`는 좌측 이미지 밑에 있으면 좋겠습니다.
- [x] 우측 상단 이미지 클릭 시 첫 페이지로 이동

**Comment by publdaze** [comment]
ba5e2cfad203ea493baf297c118098f0fcaf9086
