### ISSUE TITLE
gist 코드 스니펫이 안보이는 문제

### ISSUE THREAD

**Issue by gusah009** [gusah009/gusah009.github.io#9]
<img width="1432" alt="image" src="https://user-images.githubusercontent.com/26597702/192922547-b0231775-a9d2-4684-bc04-6c11362d1f55.png">

- [ ] gist 코드 스니펫이 안보이는 문제 해결
  - 안 될 경우 gist 코드 스니펫을 모두 로컬 코드로 변경할 예정

**Comment by publdaze** [comment]
[플러그인](https://www.gatsbyjs.com/plugins/gatsby-remark-embed-gist/) 사용하면 될 것도 같은데, 나중에 적용해보겠습니다
